export { FiscalRail, type FiscalRailOptions } from "./client.js";
export {
  APIConnectionError,
  APIError,
  APITimeoutError,
  AccountNotConfiguredError,
  AuthenticationError,
  BalanceExhaustedError,
  CustomerNotFoundError,
  FiscalRailError,
  IdempotencyConflictError,
  InvalidCustomerError,
  InvalidInvoiceAmendmentError,
  InvalidInvoiceError,
  InvalidInvoiceSeriesError,
  InvalidPaymentInstructionError,
  InvalidRequestError,
  PdfRenderInProgressError,
  PdfRenderingUnavailableError,
  ResourceNotFoundError,
  ResponseParseError,
  WebhookSignatureError,
  type ValidationDetail,
} from "./errors.js";
export {
  RESPONSE_METADATA,
  getResponseMetadata,
  type ResponseMetadata,
  type WithResponseMetadata,
} from "./response.js";
export type { BinaryContent, Fetch } from "./transport.js";
export type {
  Account,
  AccountInvoicing,
  AccountInvoicingUpdateParams,
  AccountTaxRegime,
  CertificateUploadParams,
  SpanishAccountTaxRegime,
  SpanishAccountSubmission,
  SpanishPendingSubmission,
  AccountUpdateParams,
  ApiKey,
  ApiKeyCreateParams,
  Balance,
  Customer,
  CustomerCreateParams,
  CustomerListParams,
  CustomerUpdateParams,
  Event,
  EventDestination,
  EventDestinationCreateParams,
  EventDestinationUpdateParams,
  EventListParams,
  Invoice,
  InvoiceAmendment,
  InvoiceAmendParams,
  InvoiceIssueParams,
  InvoiceListParams,
  InvoicePdf,
  InvoiceSeries,
  InvoiceSeriesCreateParams,
  InvoiceSeriesUpdateParams,
  Page,
  PageParams,
  PaymentInstruction,
  PaymentInstructionCreateParams,
  PaymentInstructionUpdateParams,
  PdfRenderOptions,
  RequestOptions,
  TaxId,
  TaxReference,
  TaxRegime,
} from "./types.js";
export { VERSION } from "./version.js";
